#!/usr/bin/ruby

puts "enter the speetch to search through"

text = gets.chomp

puts "word to redact"

redact = gets.chomp


words = text.split(" ")

words.each do |words|

	if words == redact
	print "REDACTED "

	else 
	print words + " "
        end
end
	

